server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://mysql.railway.internal:3306/product?createDatabaseIfNotExist=true
    username: root
    password: UsugGAOalKUdqHLULjrJWFORBCtsJEKg
  jpa:
    hibernate:
      ddl-auto: update