server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST:localhost}:${PROD_DB_PORT:3306}/${PROD_DB_NAME:product}?createDatabaseIfNotExist=true
    username: ${PROD_DB_USERNAME:root}
    password: ${PROD_DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update